// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package app

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/steelthedev/htmx-portfolio/view/layout"

func Index() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"page-wrapper page-wrapper-2\" data-background=\"./img/bg/page-bg-1.jpg\"><!-- header-start --><div class=\"container z-index-3\"><div class=\"row\"><!-- parsonal-info-start --><div class=\"col-12\"><div class=\"bostami-parsonal-info-area bostami-parsonal-info-2-area\"><div class=\"bostami-parsonal-info-wrap\"><!-- img --><div class=\"bostami-parsonal-info-img\"><img src=\"./img/parsonal-info/parson-img-3.png\" alt=\"\"></div><!-- name --><h4 class=\"bostami-parsonal-info-name\"><a href=\"#\">Monalisa Ashley</a></h4><span class=\"bostami-parsonal-info-bio mb-15\">Ui/Ux Designer</span><!-- socail link --><ul class=\"bostami-parsonal-info-social-link mb-30\"><li><a href=\"#\" class=\"facebook\"><i class=\"fa-brands fa-facebook-f\"></i></a></li><li><a href=\"#\" class=\"twitter\"><i class=\"fa-brands fa-twitter\"></i></a></li><li><a href=\"#\" class=\"instagram\"><i class=\"fa-brands fa-instagram\"></i></a></li><li><a href=\"#\" class=\"linkedin\"><i class=\"fa-brands fa-linkedin-in\"></i></a></li></ul><!-- cv button --><div class=\"bostami-parsonal-info-btn\"><a class=\"btn-2 circle\" href=\"#\"><span class=\"icon\"><i class=\"fa-regular fa-download\"></i></span> download cv</a></div></div></div></div><!-- personal-info-end --></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
