// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Navbar() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"bostami-header-area mb-80 z-index-5\"><div class=\"container\"><div class=\"bostami-header-wrap main-style-2\"><div class=\"row\"><!-- logo --><div class=\"col-lg-2 col-md-6 col-sm-4 col-4 d-flex align-items-center\"><div class=\"bostami-header-logo\"><a class=\"site-logo\" href=\"https://bostami-bootstrap.ibthemespro.com/index.html\"><img src=\"./img/logo/logo-2.png\" alt=\"\"></a></div></div><!-- menu btn --><div class=\"col-lg-10 col-md-6 col-sm-8 col-8\"><div class=\"header-right-flex\"><div class=\"bostami-main-menu-wrap \"><nav class=\"bastami-main-menu main_menu_2\"><ul><li><a href=\"home-2.html\"><span><i class=\"fa-light fa-house\"></i></span> home</a></li><li class=\"active\"><a href=\"about-2.html\"><span><i class=\"fa-light fa-address-card\"></i></span> about</a></li><li><a href=\"resume-2.html\"><span><i class=\"fa-light fa-file-user\"></i></span> Resume</a></li><li><a href=\"portfolio-2.html\"><span><i class=\"fa-light fa-briefcase\"></i></span> Works</a></li><li><a href=\"blog-2.html\"><span><i class=\"fa-light fa-newspaper\"></i></span> Blogs</a></li><li><a href=\"contact-2.html\"><span><i class=\"fa-light fa-address-book\"></i></span> contact</a></li></ul></nav></div><div class=\"bostami-header-menu-btn text-right ml-30\"><div class=\"dark-btn dark-btn-2\"><i class=\"fa-light fa-moon dark-btn-icon\"></i> <i class=\"fa-light fa-sun dark-btn-icon\"></i></div><div class=\"menu-btn-wrap d-lg-none\"><div class=\"menu-btn menu-btn-2 toggle_menu\"><span></span> <span></span> <span></span></div></div></div></div></div></div></div><!-- mobile menu --><div class=\"mobile-menu-wrap\"><div class=\"mobile-menu mobile_menu_2\"></div></div></div></div><!-- header-end -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func Base() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html class=\"no-js\" lang=\"zxx\"><head><meta charset=\"utf-8\"><meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\"><title>Bostami - Home Page Two </title><meta name=\"description\" content=\"\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"./img/favicon.png\"><link rel=\"stylesheet\" href=\"./css/bootstrap.min.css\"><link rel=\"stylesheet\" href=\"./css/animate.min.css\"><link rel=\"stylesheet\" href=\"./css/fontawesome.min.css\"><link rel=\"stylesheet\" href=\"./css/all.min.css\"><link rel=\"stylesheet\" href=\"./css/odometer.min.css\"><link rel=\"stylesheet\" href=\"./css/meanmenu.css\"><link rel=\"stylesheet\" href=\"./css/swipper.css\"><link rel=\"stylesheet\" href=\"./css/main.css\"></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Navbar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var2.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script src=\"/static/js/jquery.min.js\"></script><script src=\"./js/bootstrap.bundle.min.js\"></script><script src=\"./js/swipper-bundle.min.js\"></script><script src=\"./js/jquery.meanmenu.min.js\"></script><script src=\"./js/wow.min.js\"></script><script src=\"./js/odometer.min.js\"></script><script src=\"./js/appear.min.js\"></script><script src=\"./js/main.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
